### PR TITLE
Added aur package for archlinux

### PR DESCRIPTION
**Pull request by osospeed**
https://aur.archlinux.org/packages/dry/

### CODE REVIEW

**Comment by moncho** [comment]
Hi, thanks for the PR 👍 

I had made a few additional changes to the README file so instead of merging your PR, I have added archlinux instructions myself. Hope it is ok.

**Comment by osospeed** [comment]
Good.

**Comment by moncho** [comment]
I will close this PR then, ok?

**Comment by osospeed** [comment]
yes

**Pull request closed without merging**
