### PR TITLE
Add to waitgroup before starting goroutine

### PR DESCRIPTION
**Pull request by muesli**
This prevents a race condition where we potentially check the WaitGroup before
the goroutine even had a chance to start.

### CODE REVIEW

**Comment by moncho** [comment]
Not so convinced about this one. 

We want to wait for the goroutine to end before exiting the main goroutine. If `wg.Add(1)` is done inside the goroutine it might happen that the `wg.Wait()` on the main goroutine continues because the launched goroutine has not started yet. See [WaitGroup docs example](https://golang.org/pkg/sync/#WaitGroup).

**Comment by muesli** [comment]
@moncho Wait, what you describe is exactly what this is supposed to fix? Did you read the diff the wrong way round by chance? :slightly_smiling_face:

**Comment by moncho** [comment]
@muesli you are totally right and I was reading it wrong, sorry!!!

Nice fix!

**Comment by muesli** [comment]
@moncho No problem, nothing to apologize for! Keep up the great work & thanks for merging!

**Pull request merged**
